Order candidates, add precision and timestamp
datamade/block-club-election-night pull request #1
Opened 2023-03-30 21:35 UTC by hancush

See title!

2023-04-03 20:32 UTC, hancush commented on election_night/get_results.py
> +                extrasaction="ignore"
TIL! This ignores any data keys that you don't pass in as a fieldname.

2023-04-03 22:23 UTC, derekeder requested changes
@hancush getting an error when running:

```bash
(elections) derekeder@Rhodes block-club-election-night % python -m election_night.get_results --precinct --election="2023 Municipal General - 2/28/2023"
Getting precinct results for 2023 Municipal General - 2/28/2023! 🎉
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/derekeder/projects/datamade/block-club-election-night/election_night/get_results.py", line 161, in <module>
    PrecinctClient()[options.election]
KeyError: '2023 Municipal General - 2/28/2023'
```

getting a similar error when running:

```bash
(elections) derekeder@Rhodes block-club-election-night % python -m election_night.get_results --precinct
Getting precinct results for 2023 Municipal Runoffs - 4/4/23! 🎉
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/derekeder/projects/datamade/block-club-election-night/election_night/get_results.py", line 161, in <module>
    PrecinctClient()[options.election]
KeyError: '2023 Municipal Runoffs - 4/4/23'
```

2023-04-04 13:40 UTC, hancush commented
@derekeder Whoops, forgot to instruct you to upgrade your requirements. Run this, then the test commands: `pip install --upgrade --no-cache-dir -r requirements.txt`

2023-04-04 14:28 UTC, derekeder approved these changes
@hancush ok after deleting my virtual environment and recreating and installing from scratch, the scraper commands ran as expected.

my only note/suggestion would be - if we're giving the ability to choose which election to scrape, it would be helpful to use that to name the folder the results go in. i ran both the runoff and the feb 28 back to back and i had to inspect the files in each folder to know which was which.

2023-04-04 14:36 UTC, merged